name: 'Lint GraphQL operation files'
description: 'Checks operation files against a schema to find deprecated fields'
author: 'digiz3d'

branding:
  color: 'orange'
  icon: 'trash'

inputs:
  schema-file:
    description: 'Path to the schema file to use as reference'
    required: true
  operation-files-glob:
    description: 'Glob to the operation file(s) to check against the schema'
    required: true
  report-files:
    description: 'Indicate wether to report the paths of the files with deprecated fields'
    default: 'true'

runs:
  using: 'node20'
  main: 'dist/index.js'
